---
version: '2.1'
services:
  django:
    container_name: ssl_pki_django
    env_file: env
    image: ssl_pki_django:latest
    build:
      context: .
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8808/admin || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    ports:
      - 8808:8808
    networks:
      default:
        aliases:
          - django-pki.boundless.test
    volumes:
      - $PWD:/code:rw  # needed for running tests and coverage
      - ssl_pki_django_media:/app/data/media
  nginx:
    container_name: ssl_pki_nginx
    image: ssl_pki_nginx:latest
    build: ./docker/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail http://localhost:8881"]
      interval: 60s
      timeout: 15s
      retries: 10
    ports:
      - 8880:8880
      - 8444:8444
      - 8881:8881
      - 8445:8445
    networks:
      default:
        aliases:
          - nginx-pki.boundless.test
          - endpoint-pki.boundless.test
    depends_on:
      - django
    volumes:
      - $PWD/docker/nginx/sites-available:/etc/nginx/sites-available:rw
volumes:  # volumes with no displayed path/relationship to the host
  ssl_pki_django_media:
